- name: titlebar buttons
  shell: DISPLAY=:1.0 xfconf-query -c xfwm4 -p /general/button_layout -s 'CHM|O'
  ignore_errors: yes

- name: power settings
  command: "{{item}}"
  with_items:
  - DISPLAY=:1.0 xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/lid-action-on-battery -s 0
  - DISPLAY=:1.0 xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/lid-action-on-ac -s 0
  - DISPLAY=:1.0 xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/show-tray-icon -s 1
  ignore_errors: yes # This fails if the xfce4-power-manager settings menu has not been opened yet. Fix later.

- name: set wallpaper
  shell: DISPLAY=:1.0 xfconf-query --channel xfce4-desktop --property /backdrop/screen0/monitor0/image-path --set ~/syncthing/Wallpaper/shards-pink.jpg
  ignore_errors: yes # This fails if the wallpaper settings menu has not been opened yet. Fix later.

- name: update rc.local
  copy:
    src: "{{myconfig.dir}}/chromebook/rc.local"
    dest: /etc/rc.local
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  become: yes
  become_method: sudo

- name: copy crouton shares
  copy:
    src: "{{myconfig.dir}}/chromebook/crouton-shares"
    dest: /etc/crouton/shares
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: yes
  become_method: sudo


- name: unmount ~/Downloads
  command: umount ~/Downloads

- name: delete old downloads
  command: rmdir ~/Downloads
