- name: add repos
  apt_repository:
    repo: "{{item}}"
    state: present
    #codename: yes # supported in verison 2.3
  with_items:
  - deb https://riot.im/packages/debian/ xenial main
  - deb https://apt.syncthing.net/ syncthing stable
  become: yes
  become_method: sudo

- name: install packages
  apt:
    name: "{{installed_packages}}"
    state: present
  become: yes
  become_method: sudo

#- name: download repo keys
#  get_url:
#    url: "{{item.url}}"
#    dest: "{{item.dest}}"
#  with_items: "{{deb_repo_keys}}"
#
#- name: add repo keys
#  command: apt-key add "{{item.dest}}"
#  become: yes
#  become_method: sudo
#  with_items: "{{deb_repo_keys}}"

- name: remove packages
  apt:
    name: xscreensaver
    state: absent
    autoremove: yes
  become: yes
  become_method: sudo

- name: download deb files
  get_url:
    url:  "{{item.url}}"
    dest: "{{item.dest}}"
  with_items: "{{deb_installs}}"

- name: install deb files
  shell: yes | gdebi "{{item.dest}}"
  become: yes
  become_method: sudo
  args:
    creates: "{{item.bin_path}}"
  with_items: "{{deb_installs}}"

- name: install pip packages
  pip:
    name: "{{item}}"
    executable: pip3
  with_items:
    - khal
    - tootstream
    - vdirsyncer

- name: generate locales
  command: "{{item}}"
  become: yes
  become_method: sudo
  with_items:
    - "locale-gen en_US.UTF-8"
    - "update-locale"

- name: install nemutt dependencies
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - libidn11-dev
    - libncursesw5-dev
    - libnotmuch-dev
    - libsasl2-dev
    - libxml2-utils
    - offlineimap
    - urlview
    - xsltproc
  become: yes
  become_method: sudo

- name: download neomutt
  git:
    repo: "{{neomutt.repo_http}}"
    dest: "{{neomutt.dir}}"
    accept_hostkey: yes

- name: configure neomutt
  command: './configure --disable-doc --notmuch --sasl'
  args:
    chdir: "{{neomutt.dir}}"

- name: make neomutt
  make:
    chdir: "{{neomutt.dir}}"

- name: install neomutt
  make:
    chdir: "{{neomutt.dir}}"
    target: install
  become: yes
  become_method: sudo

- name: update font cache
  command: fc-cache -f

