alias ls='ls --color -hF'
alias l='ls --color -hF'
alias la='ls --color -AhF'
alias ll='ls --color -lhF'
alias lla='ls --color -lAhF'

alias pvi='vi -'
alias vi='vi -p'

alias gl='git lg'
alias glh='git lg|head'
alias gs='git status'

alias du='du -hs'

alias df='df -h'

alias grep='grep --color'
alias ag='ag --color-path=35'

alias thanks="echo you\'re welcome! \<3"

# to train myself to use vi command
alias vim='echo no use vi'
