# Mac's ls has a different option for colored output
if [ "$(which sw_vers)" ]; then
	color_opt="-G"
else
	color_opt="--color"
fi
alias ls='ls ${color_opt} -hF'
alias l='ls ${color_opt} -hF'
alias la='ls ${color_opt} -AhF'
alias ll='ls ${color_opt} -lhF'
alias lla='ls ${color_opt} -lAhF'

alias pvi='vi -'
alias vi='vi -p'

alias gl='git lg'
alias glh='git lg|head'
alias gs='git status'

alias du='du -hs'

alias df='df -h | grep -E --color=never "(Filesystem)|(/dev/sd)"'

alias grep='grep --color'
alias ag='ag --color-path=35'

alias thanks="echo you\'re welcome! \<3"

# to train myself to use vi command
alias vim='echo no use vi'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
if [ "$(which sw_vers)" ]; then
	alias alert='osascript -e "display alert \"command finished\""'
else
	alias alert='notify-send --urgency=critical -i "$([ $? = 0 ] && echo terminal || echo error)" "command finished"'
fi

alias k=kubectl
