# If not running interactively, don't do anything
case $- in
    *i*) ;;
        *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# Disable flow control so Ctrl-s doesn't lock up bash
stty -ixon

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# Set the P1 prompt options
prompt_char="\[\033[38;5;1m\]$"

# Aliases
[ -r ~/.bash_aliases ] && . ~/.bash_aliases

# Machine Specific bashrc
[ -r ~/.bashrc_local ] && . ~/.bashrc_local

# Set the prompt
PS1="\[\033[38;5;128m\]\u\[\033[38;5;15m\] \w ${prompt_char}\[\033[38;5;15m\] \[$(tput sgr0)\]"

# Enable bash completion
if ! shopt -oq posix; then
    if [ -f /usr/share/bash-completion/bash_completion ]; then
        . /usr/share/bash-completion/bash_completion
    elif [ -f /etc/bash_completion ]; then
        . /etc/bash_completion
    fi
fi

# Print pride flag
[ -r ~/.bash-pride-flags/short.sh ] && . ~/.bash-pride-flags/short.sh

# silence this warning on Mac
export BASH_SILENCE_DEPRECATION_WARNING=1
