# Mac's ls has a different option for colored output
if [ "$(which sw_vers 2> /dev/null)" ]; then
    color_opt="-G"
else
    color_opt="--color"
fi
alias ls='ls ${color_opt} -hF'
alias l='ls ${color_opt} -hF'
alias la='ls ${color_opt} -AhF'
alias ll='ls ${color_opt} -lhF'
alias lla='ls ${color_opt} -lAhF'

alias pvi='vi -'
alias vi='vi -p'

alias gl='git lg'
alias glh='git lg|head'
alias gs='git status'

alias du='du -hs'

alias df='df -h'

alias grep='grep --color'
alias ag='ag --color-path=35'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
if [ "$(which sw_vers 2> /dev/null)" ]; then
    alias alert='osascript -e "display alert \"command finished\""'
else
    alias alert='notify-send --urgency=critical -i "$([ $? = 0 ] && echo terminal || echo error)" "command finished"'
fi

alias k=kubectl

alias ansi='ansible-playbook -i hosts playbook.yml'

alias mus='cd ~/music && cmus'

alias ffind='find . -name '

alias youtube-dl-song='youtube-dl -o "%(title)s.%(ext)s" -x --audio-format mp3 '
function youtube-dl-playlist {
    yt_link=$1
    mkdir -p ./tmp/
    (cd ./tmp && youtube-dl --verbose -o "TRACKNUM%(playlist_index)sTRACKNUMEND%(title)s.%(ext)s" -k -x --audio-format mp3 $yt_link)
    for i in ./tmp/TRACKNUM*.mp3; do
        echo "modifying" "$i"
        tracknum=$(echo $i | sed 's/\.\/tmp\/TRACKNUM\(.*\)TRACKNUMEND.*/\1/')
        videoname=$(echo $i | sed 's/^.*TRACKNUMEND\(.*\)/\1/')
        echo $tracknum
        echo $videoname
        id3v2 --track $tracknum "$i"
        cp "$i" "$videoname"
    done
    echo
    echo
    echo 'Commands to run:'
    echo 'Set album: id3v2 --artist $ALBUM_NAME *mp3'
    echo 'Remove xyz from filenames: rename -n ''s/xyz//'' *.mp3'
    echo 'Set track names: set-all-track-names'
    echo 'Delete temp: rm tmp'
}

function set-all-track-names {
    for i in *.mp3; do
        track=$(echo $i | sed 's/\.mp3//')
        id3v2 --song "$track" "$i"
    done
}

alias awk1="awk '{print $1}'"
alias awk2="awk '{print $2}'"
alias awk3="awk '{print $3}'"

alias kd='kubectl describe'
alias kdp='kubectl describe pod'
alias kl='kubectl logs'
alias klf='kubectl logs -f'

alias vba='source venv/bin/activate'
