all:
  children:
    desktop:
      hosts:
        corriander:
          ansible_port: 22
          ansible_host: 192.168.3.2
    crouton:
      hosts:
        redpepper:
          ansible_port: 22
          ansible_host: 192.168.3.10
        greenpepper:
          ansible_port: 22
          ansible_host: 192.168.3.11
    pi:
      hosts:
        ginger:
          ansible_port: 22
          ansible_host: 192.168.3.7
    vms:
      hosts:
        cilantro:
          ansible_port: 22
          ansible_host: 192.168.3.20

  vars:
    myconfig:
      dir:        ~/.myconfig
      repo_http:  https://github.com/samclotf/My-System-Config.git
      repo_ssh:   git@github.com:samclotf/My-System-Config.git
