all:
  children:
    desktop:
      hosts:
        kuruk:
          ansible_port: 22
          ansible_host: 192.168.3.2
    crouton:
      hosts:
        chromebook1:
          ansible_port: 22
          ansible_host: 192.168.3.10
        chromebook2:
          ansible_port: 22
          ansible_host: 192.168.3.11
    pi:
      hosts:
        pi1:
          ansible_port: 22
          ansible_host: 192.168.3.7

  vars:
    myconfig:
      dir:        ~/.myconfig
      repo_http:  https://github.com/samclotf/My-System-Config.git
      repo_ssh:   git@github.com:samclotf/My-System-Config.git
