all:
  children:
    desktop:
      hosts:
        corriander:
          ansible_port: 22
          ansible_host: 192.168.3.2
          ansible_become_pass: "{{ lookup('file', 'become.vault') }}"
    crouton:
      hosts:
        redpepper:
          ansible_port: 22
          ansible_host: 192.168.3.10
          ansible_become_pass: "{{ lookup('file', 'become.vault') }}"
        greenpepper:
          ansible_port: 22
          ansible_host: 192.168.3.11
          ansible_become_pass: "{{ lookup('file', 'become.vault') }}"
    pi:
      hosts:
        ginger:
          ansible_port: 22
          ansible_host: 192.168.3.7
          ansible_become_pass: "{{ lookup('file', 'become.vault') }}"
    vms:
      hosts:
        cilantro:
          ansible_port: 22
          ansible_host: 192.168.3.20
          ansible_become_pass: "{{ lookup('file', 'become.vault') }}"

  vars:
    myconfig:
      dir:        ~/.myconfig
      repo_http:  https://github.com/samclotf/My-System-Config.git
      repo_ssh:   git@github.com:samclotf/My-System-Config.git
