# Things to bring into ansible
#
#
# Add this to session startup automatically
# ~/.myconfig/chromebook/login.sh
#
# find how to edit xfce properties before they initialize
#
# Use these themes
# - https://www.xfce-look.org/p/999991/
#   (Breeze-Purple)
# - https://www.xfce-look.org/p/1016679/
#   (axiomd)
# - Icons: Ubuntu-Mono-Dark

---
- hosts: all
  roles:
    - common

- hosts: pi
  roles:
    - radicale

- hosts: desktop
  roles:
    - gui

- hosts: crouton
  roles:
    - gui
    - crouton
