# Things to bring into ansible
#
#
# Add this to session startup automatically
# ~/.myconfig/chromebook/login.sh
#
# add a new email client and its config
#
# find how to edit xfce properties before they initialize
#
# autostart tmux with some common cli programs
#
# Use these themes
# - https://www.xfce-look.org/p/999991/
#   (Breeze-Purple)
# - https://www.xfce-look.org/p/1016679/
#   (axiomd)
# - Icons: Ubuntu-Mono-Dark

---
- hosts: all
  tasks:


- hosts: desktop
  roles:
    - common
    - gui

- hosts: crouton
  roles:
    - common
    - gui
    - crouton
